package com.quronest.quronest_backend.service;

import com.quronest.quronest_backend.dto.AnchorDto;
import com.quronest.quronest_backend.dto.DailyTaskDto;
import com.quronest.quronest_backend.dto.JobStatusDto;
import com.quronest.quronest_backend.dto.llm.LLMDailyPlanContextDto;
import com.quronest.quronest_backend.dto.llm.LLMTaskContextDto;
import com.quronest.quronest_backend.dto.llm.LLMTaskGenerateContextDto;
import com.quronest.quronest_backend.dto.llm.LLMUserContextDto;
import com.quronest.quronest_backend.exception.DailyTaskAlreadyGeneratedException;
import com.quronest.quronest_backend.exception.DailyTaskNotFoundException;
import com.quronest.quronest_backend.model.QuizTaskContent;
import com.quronest.quronest_backend.model.ReadingTaskContent;
import com.quronest.quronest_backend.model.enums.DailyTaskType;
import com.quronest.quronest_backend.model.enums.JobType;
import com.quronest.quronest_backend.model.table.DailyTask;
import com.quronest.quronest_backend.model.table.Job;
import com.quronest.quronest_backend.model.table.User;
import com.quronest.quronest_backend.repository.AnchorRepository;
import com.quronest.quronest_backend.model.table.DailyTaskLog;
import com.quronest.quronest_backend.repository.DailyTaskLogRepository;
import com.quronest.quronest_backend.repository.DailyTaskRepository;
import com.quronest.quronest_backend.service.rabbit.JobProducerService;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Service
public class DailyTaskService {

    private final DailyTaskRepository dailyTaskRepository;
    private final DailyTaskLogRepository dailyTaskLogRepository;
    private final JobProducerService jobProducerService;
    private final UserService userService;
    private final LLMContextService llmContextService;
    private final LLMApiService llmApiService;

    private final List<DailyTaskType> ALLOWED_ANCHOR_TASK_TYPES = List.of(DailyTaskType.READING);
    private final AnchorRepository anchorRepository;

    public DailyTaskService(DailyTaskRepository dailyTaskRepository,
                            DailyTaskLogRepository dailyTaskLogRepository,
                            JobProducerService jobProducerService,
                            UserService userService, LLMContextService llmContextService, LLMApiService llmApiService,
                            AnchorRepository anchorRepository) {
        this.dailyTaskRepository = dailyTaskRepository;
        this.dailyTaskLogRepository = dailyTaskLogRepository;
        this.jobProducerService = jobProducerService;
        this.userService = userService;
        this.llmContextService = llmContextService;
        this.llmApiService = llmApiService;
        this.anchorRepository = anchorRepository;
    }

    public JobStatusDto createTaskGenerateJob(UUID taskId) {
        User user = userService.getAuthenticatedUser();
        DailyTask task = dailyTaskRepository.findByIdAndUser(taskId, user);
        if (task == null) {
            throw new DailyTaskNotFoundException();
        }

        // verify task already generated by its version
        if (task.getVersion() > 0) {
            throw new DailyTaskAlreadyGeneratedException();
        }

        JobStatusDto jobStatusDto = new JobStatusDto();
        switch (task.getTaskType()) {
            case READING -> {
                jobStatusDto = createTaskGenerateJob(task, JobType.LLM_GENERATE_DAILY_TASK_READING);
            }
            case QUIZ -> {
                jobStatusDto = createTaskGenerateJob(task, JobType.LLM_GENERATE_DAILY_TASK_QUIZ);
            }
        }

        task.getInternalData().setJobId(jobStatusDto.getJobId());
        dailyTaskRepository.save(task);

        return jobStatusDto;
    }

    public JobStatusDto createTaskGenerateJob(DailyTask task, JobType jobType) {
        // (currently allowing only one reading job at a time for a user).
        jobProducerService.verifyExistedJobAndThrow(task.getUser(), jobType,
                                                    "A same type task generation is already in progress.");

        // create the llm context
        LLMUserContextDto userContextDto = llmContextService.getUserContext(task.getUser());
        LLMTaskContextDto taskContextDto = new LLMTaskContextDto(task);
        LLMDailyPlanContextDto planContextDto = new LLMDailyPlanContextDto(task.getPlan());

        LLMTaskGenerateContextDto taskGenerateContextDto = new LLMTaskGenerateContextDto(task.getId(), taskContextDto,
                                                                                         userContextDto,
                                                                                         planContextDto);

        Job job = jobProducerService.createAndSendNewJob(task.getUser(), jobType,
                                                         taskGenerateContextDto);

        return new JobStatusDto(job);
    }

    public DailyTask completeReadingTaskGeneration(User user,
                                                   LLMTaskGenerateContextDto taskGenerateContextDto) {
        DailyTask task = dailyTaskRepository.findByIdAndUserAndTaskType(taskGenerateContextDto.getTaskId(), user,
                                                                        DailyTaskType.READING);
        if (task == null) {
            throw new DailyTaskNotFoundException();
        }

        // generate response
        ReadingTaskContent taskContent = llmApiService.generateReadingTask(taskGenerateContextDto);

        // set context to task
        task.setContentJson(taskContent);
        task.incrementVersion();
        task.setLastGeneratedAt(LocalDateTime.now());

        dailyTaskRepository.save(task);

        return task;
    }

    public DailyTask completeQuizTaskGeneration(User user,
                                                LLMTaskGenerateContextDto taskGenerateContextDto) {
        DailyTask task = dailyTaskRepository.findByIdAndUserAndTaskType(taskGenerateContextDto.getTaskId(), user,
                                                                        DailyTaskType.QUIZ);
        if (task == null) {
            throw new DailyTaskNotFoundException();
        }

        // generate response
        QuizTaskContent taskContent = llmApiService.generateQuizTask(taskGenerateContextDto);

        // set context to task
        task.setContentJson(taskContent);
        task.incrementVersion();
        task.setLastGeneratedAt(LocalDateTime.now());

        dailyTaskRepository.save(task);

        return task;
    }

    public DailyTaskDto getTaskById(UUID taskId) {
        User user = userService.getAuthenticatedUser();
        DailyTask task = dailyTaskRepository.findByIdAndUser(taskId, user);

        if (task == null) {
            throw new DailyTaskNotFoundException();
        }

        if (!ALLOWED_ANCHOR_TASK_TYPES.contains(task.getTaskType())) {
            return new DailyTaskDto(task);
        }

        // find anchors
        List<AnchorDto> anchorDtos = anchorRepository.findByReferenceId(taskId).stream().map(AnchorDto::new).toList();
        return new DailyTaskDto(task, anchorDtos);
    }

    public DailyTaskLog getOrCreateTaskLog(DailyTask task, User user) {
        DailyTaskLog taskLog = dailyTaskLogRepository.findByTaskAndUser(task, user);
        if (taskLog == null) {
            taskLog = new DailyTaskLog();
            taskLog.setTask(task);
            taskLog.setUser(user);
            if (task != null) {
                taskLog.setPlan(task.getPlan());
                taskLog.setStatus(task.getStatus());
            }
            taskLog.setStartedAt(LocalDateTime.now());
            taskLog.setAttempts(0);
            taskLog.setTotalTimeSpent(0);
            taskLog.setMaxScore(0.0);
            taskLog.setProgressPercent(0);
            dailyTaskLogRepository.save(taskLog);
        }
        return taskLog;
    }

}
