spring.application.name=quronest_backend

spring.main.banner-mode=off
server.servlet.context-path=/backend

############### Database ##############
spring.datasource.url= jdbc:postgresql://localhost:5434/postgres
spring.datasource.username= postgres
spring.datasource.password= root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Validate tables
spring.jpa.hibernate.ddl-auto=validate

############### Liquibase ##############
# Do not run automatically at start
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.json

########### Swagger ###################
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.csrf.enabled=true
#### Uncomment the following to disable swagger:
#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false