server.port=8080
spring.application.name=quronest_backend
server.forward-headers-strategy=framework

spring.main.banner-mode=off
server.servlet.context-path=/backend

############### Database ##############
spring.datasource.url= jdbc:postgresql://localhost:5434/postgres
spring.datasource.username= postgres
spring.datasource.password= root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Validate tables
spring.jpa.hibernate.ddl-auto=validate

############### Liquibase ##############
# Do not run automatically at start
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.json

########### Swagger ###################
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.csrf.enabled=true
#### Uncomment the following to disable swagger:
#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false

########### Jwt ###################
security.jwt.access-token-secret=skdjhkdsajhkdfjghdfkjbnjkbnjfbdgjhgkfjnbdjfbhfdjghjkgh
security.jwt.access-token-expiry=54000000
security.jwt.refresh-token-secret=skdjhkdsajhkdfjghdfkjbnjkbnjfbdgjhgkfjnbdjfbhfdjghjkgh
security.jwt.refresh-token-expiry=64000000
security.jwt.private-key-path=deployment/dev/keys/private.pem
security.jwt.public-key-path=deployment/dev/keys/public.pem

########### COOKIE ##############
security.cookie.access-token-max-age=900
security.cookie.refresh-token-max-age=604800
security.cookie.secure=true

################# OAuth2 Client #######################
quronest.google_client_id=65407990403-virc7qq6k86c1vqro5uuejg1otseci2a.apps.googleusercontent.com
quronest.google_client_secret=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

quronest.github_client_id=Ov23li2DASiynPAdRAjz
quronest.github_client_secret=24ee3d6af0e8147dcece99c41258dc1f8284b717

################### Security params ###################
security.custom.frontendbaseurl=https://localhost.quronest.com
security.custom.llmservicebaseurl=http://localhost.quronest.com/llm/api/v1

############## RabbitMQ ################
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

################ Serialization ################
spring.mvc.converters.preferred-json-mapper=jackson

################ Quiz Config ################
quronest.quiz-pass-threshold=30.0