server.port=8080
spring.application.name=quronest_backend

spring.main.banner-mode=off
server.servlet.context-path=/backend

############### Database ##############
spring.datasource.url= jdbc:postgresql://localhost:5434/postgres
spring.datasource.username= postgres
spring.datasource.password= root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Validate tables
spring.jpa.hibernate.ddl-auto=validate

############### Liquibase ##############
# Do not run automatically at start
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.json

########### Swagger ###################
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.csrf.enabled=true
#### Uncomment the following to disable swagger:
#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false

########### Jwt ###################
security.jwt.access-token-secret=skdjhkdsajhkdfjghdfkjbnjkbnjfbdgjhgkfjnbdjfbhfdjghjkgh
security.jwt.access-token-expiry=54000000
security.jwt.refresh-token-secret=skdjhkdsajhkdfjghdfkjbnjkbnjfbdgjhgkfjnbdjfbhfdjghjkgh
security.jwt.refresh-token-expiry=64000000

########### COOKIE ##############
security.cookie.access-token-max-age=900
security.cookie.refresh-token-max-age=604800
security.cookie.secure=false
