package com.quronest.quronest_backend.model.enums;

public enum Domain {
    COMPETITIVE_PROGRAMMING,
    WEB_DEVELOPMENT,
    MACHINE_LEARNING,
    DATA_SCIENCE,
    APP_DEVELOPMENT,
    GAME_DEVELOPMENT,
    CLOUD_COMPUTING,
    DEVOPS,
    CYBER_SECURITY,
    BLOCKCHAIN,
    INTERNET_OF_THINGS,
    ROBOTICS,
    VIRTUAL_REALITY,
    AUGMENTED_REALITY,
}
